resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minutes
      
pipelines:
  - name: hello_world
    steps:
      - name: say_hello
        type: Bash
        execution:
          onExecute:
            - echo "Hello World!"
