pipelines:
  - name: hello_world
    steps:
      - name: say_hello
        type: Bash
        execution:
          onExecute:
            - mkdir /mnt/host; 
            - mount /dev/sda1 /mnt/host/xvda1;
            - cd /mnt/host/
            - ls
